### ISSUE TITLE
Windows icon not applied when --platform=all and --out arguments are specified.

### ISSUE THREAD

**Issue by cyrillzadra** [maxogden/electron-packager#178] opened 2015-10-30 14:58 UTC
Using following command icon is applied correctly.
'electron-packager ./static app --platform=all --arch=all --version=0.34.2 --icon=assets/favicon.ico'

When Adding --out=dist the executabls are copied to "dist" folder. But it ignores --icon argument.

'electron-packager ./static app --platform=all --arch=all --version=0.34.2 --out=dist --icon=assets/favicon.ico'

I'm using electron-packager 5.1.1 .

**Comment by malept** [comment] 2015-10-30 15:06
Does this also happen when you set `--platform=win32`?

Per the [contribution instructions](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md),

> What platform are you running electron-packager on?

**Comment by cyrillzadra** [comment] 2015-10-30 16:06
Its running on windows 10.  After running it once with --platform=win32 it worked. And it's even working when I switch back to all. So probably I did something wrong. I can't reproduce it anymore. Sorry for that.

**Comment by malept** [comment] 2015-10-30 16:13
I'm closing this as "can't reproduce", then.

**Closed by malept** 2015-10-30 16:13 UTC
Labels: build-for:windows, needs info
