### ISSUE TITLE
we need some tests!

### ISSUE THREAD

**Issue by maxogden** [maxogden/electron-packager#77] opened 2015-06-18 04:09 UTC
lots of people are using this but nobody has written a test suite yet to catch regressions!

guidelines:

- we would prefer https://www.npmjs.com/package/tape
- keep things simple, focused on catching regressions. we can figure out proper x-platform dockerized integration testing etc in the future.
- our current 'test' command just [runs standard](https://github.com/maxogden/electron-packager/blob/554f3b735483319450c2ad8d0e0cba90e041ebe2/package.json#L35). make sure to keep that (e.g. `standard && tape tests/*.js`)

**Comment by jden** [comment] 2015-06-18 16:15
yes, yes, yes!

**Comment by kfranqueiro** [comment] 2015-06-21 00:26
My work to support `--all` eventually led me on a quest to refactor a bunch of things that should have been written in one place but instead were written in 3 places, sometimes inconsistently.  I have completed my refactoring but I figure I have a bunch of regression testing to do as a result, and am hoping to put some thought into automated tests at the same time.

My current work-in-progress is [here](https://github.com/kfranqueiro/electron-packager/commits/refactor).  I realize this might be springing a rather large surprise, but I do hope it can make things generally more consistent, and perhaps even work in fixes to a few other issues that are out there.  Let me know if you want to talk about it or anything (I'm kgf on freenode).

**Comment by kfranqueiro** [comment] 2015-06-26 04:04
Just poking in to say I'm not quite dead yet and haven't forgotten about this.  I have one unit test left to write on my [refactor branch](https://github.com/kfranqueiro/electron-packager/commits/refactor), then I need to make sure I document all the things, catch-up against master, and clean up the history.

**Comment by maxogden** [comment] 2015-06-28 00:54
I was merging pull requests today at an airport and ended up writing a *very* basic test suite: https://github.com/maxogden/electron-packager/blob/master/test/test.js

@kfranqueiro I had forgotten about your comment above + your fork until just now coming here to comment. I am happy to work with you on merging what I just did with what you have in the works.

**Comment by kfranqueiro** [comment] 2015-06-28 01:00
Heh, yeah just noticed some e-mails telling me things got merged, I have some rebasing to do again tomorrow :P also looks like you took care of one of the things my refactor was taking care of anyway.

I'll figure out what to do with my branch, I think I am hitting some of the same bases so in some cases it will basically result in code being moved around.  I will probably still essentially replace what's in the tests folder on master, since I am kicking things a lot more exhaustively already.

**Closed** 2015-07-01 19:54 UTC
Labels: help wanted
