### ISSUE TITLE
Support MAS prebuilt

### ISSUE THREAD

**Issue by positlabs** [maxogden/electron-packager#260] opened 2016-02-09 02:12 UTC
I tried specifying "mas" as the platform, but it doesn't work. I'm guessing we just need to add a string somewhere to get it to work. 

https://github.com/atom/electron/releases/download/v0.36.7/electron-v0.36.7-mas-x64.zip

**Comment by malept** [comment] 2016-02-09 02:16
Hi, thanks for filing an issue. This is actually a duplicate of #163, which has a partially-complete pull request in #223.

**Closed by malept** 2016-02-09 02:16 UTC
Labels: build-for:mac, duplicate

**Comment by positlabs** [comment] 2016-02-09 02:18
Nice, thanks!
