### ISSUE TITLE
FileVersion may not be set correctly

### ISSUE THREAD

**Issue by webarchymeta** [maxogden/electron-packager#165] opened 2015-10-22 08:39 UTC
I am packaging an application on Windows 7, 64 bit with electron (0.34.0) and specified
```
--version-string.FileVersion=0.5.0.0
```
on the command line. But the output executable still has the FileVersion of the electron (0.34.0.0) not the one I specified, namely 0.5.0.0. This is printed inside the tooltip when moving the mouse cursor over the file name.

**Comment by malept** [comment] 2015-10-22 14:52
Per the [contributing instructions](https://github.com/maxogden/electron-packager/blob/master/CONTRIBUTING.md), which version of electron-packager are you using?

**Comment by webarchymeta** [comment] 2015-10-22 20:22
5.1.0

**Comment by malept** [comment] 2015-10-23 14:35
This is a duplicate of #129.

**Closed by malept** 2015-10-23 14:35 UTC
Labels: duplicate

**Comment by malept** [comment] 2015-10-23 14:37
Could you please test the change in #143 and report back in that PR?

**Comment by webarchymeta** [comment] 2015-10-23 21:09
I had no knowledge of how to do it here on github under such a scenario. If you could get me started on it, I will test it, thanks.

**Comment by malept** [comment] 2015-10-23 21:30
Look up how to set your electron-packager dependency in `package.json` to a github repo + specific branch.
